name: Docker Build and Push

on:
  push:
    branches:
      - master
  tags:
    - 'v1.2.6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t 9025091158/ubuntu-vnc-novnc-container:v1.2.6 .

    - name: Push Docker image
      run: |
        docker push 9025091158/ubuntu-vnc-novnc-container:v1.2.6
